### ISSUE TITLE
Normalize appended data?

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-facebook#11]
I noticed that in the appended data, there are two postal codes ([one](https://github.com/activeprospect/leadconduit-integration-facebook/blob/add-metadata/src/get_lead.coffee#L56), [two](https://github.com/activeprospect/leadconduit-integration-facebook/blob/add-metadata/src/get_lead.coffee#L60)), two state fields ([one](https://github.com/activeprospect/leadconduit-integration-facebook/blob/add-metadata/src/get_lead.coffee#L54), [two](https://github.com/activeprospect/leadconduit-integration-facebook/blob/add-metadata/src/get_lead.coffee#L59)), and two places for consumer name ([one](https://github.com/activeprospect/leadconduit-integration-facebook/blob/add-metadata/src/get_lead.coffee#L53), [two](https://github.com/activeprospect/leadconduit-integration-facebook/blob/add-metadata/src/get_lead.coffee#L63-L64)).

Does it make sense to consolidate some of these fields? I worry that having things spread around like this will put the onus on the user to figure out which field has the value populated before they can create a rule or mapping.

**Comment by cgrayson** [comment]
In the course of verifying that it's possible to get leads with both of each pair (e.g., both `post_code` and `zip_code`), I found that the Facebook UI actually prevents it (when you click the "Post Code" checkbox, it disables the "Zip Code" checkbox). :confused: 

So: good call. I'll normalize them to:
1. `first_name` & `last_name`
2. `postal_code`
3. `state`
