### ISSUE TITLE
Unknown webhook mode

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-facebook#2]
What happens if the `mode` is something other than subscribe? It looks we'll get an inbound lead with `facebook: {}`. Is that OK/expected/correct?

https://github.com/activeprospect/leadconduit-integration-facebook/blob/add-metadata/src/webhook.coffee#L40

**Comment by cgrayson** [comment]
I don't think there are other `mode` values that matter to LC, but I still think it's worth having that `if` check. Adding a comment.
