### ISSUE TITLE
Inbound integration name

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-facebook#4]
Do you suppose that "Webhook" is the best name for the inbound integration? Webhook seems pretty tech jargon-y but that's probably appropriate if it's called Webhook on the Facebook side. I guess I'm just curious if you considered other names and ruled that out.

**Comment by cgrayson** [comment]
Yeah, they are called "webhooks" in the Facebook configuration. Or "callbacks", but that's probably even more tech jargon-y.
